---
:global:
  maintainer: 'community'
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
.travis.yml:
  go:
    - 1.6.4
    - 1.7.4
  env:
    global:
    - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
    - TEST_TYPE=small
