---
:global:
  maintainer: 'community'
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
.travis.yml:
  go:
    - 1.6.x
    - 1.7.x
  env:
    global:
    - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    - GLIDE_HOME="${HOME}/.glide"
    matrix:
    - TEST_TYPE=small
  # This is the deploy.on.condition.$TRAVIS_GO_VERSION we use to build binaries. See:
  # https://github.com/travis-ci/docs-travis-ci-com/pull/889
  release:
    travis_go_version: '^1\.7\.[0-9]+$'
